
Direction.create!([
  {title: "Working in the window", body: "<h4>Welcome!</h4><div>This is your first entry into the EE training experience. &nbsp;<br><br>First thing on our list is this box.&nbsp; This is where you will find all of the directions to the different lessons in each scenario.&nbsp;<br><br>This has important information that will help you succeed in completing each of these scenarios and the EE training course.&nbsp;<br><br></div><h4>First things first</h4><div>You see the small hamburger shape below the words Expression Engine Training at the top of this page? &nbsp;<strong>Click it!&nbsp;</strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<strong>Click it again!</strong><br><br>This is where you will find all of the lessons for each scenario.<br><br>Now, add some words in the title and put some text in the large text area in the middle and his create entry.<br><br><br></div>", information: "This is where we learn about some of the functions of this main window", scenario_id: "3"},
  {title: "Wow! Text Appeared!", body: "<h3>MAGIC!</h3><div>This isn't magic, just the power of your web browser put to work.&nbsp; When you type in the title box at the top, it prints the title as you would see it in the live version of the webpage you are working on.<br><br>Enter:&nbsp;</div><pre>Hello And Welcome</pre><div>into the title bar.<br><br>Just below the place where you put your title is what we call the wysiwyg.... okay that doesn't make sense, that's cause it's an acronym it means \"What you see is what you get\". &nbsp;<br><br>This is relatively true.&nbsp; There are some minor differences between what the wysiwyg will show you and what reality will be, but we'll experiment with that later.&nbsp;<br><br>Here you can do pretty close to just basic things you word processor allows you to. Make text bold, italic, add a hyper link. but here we have a few extra things. &nbsp;<br><br>add some text and check out what the different buttons will do to your text. &nbsp;after you've entered some and added some of your own fair click on the create entry and we'll get into these buttons with more detail.</div>", information: "", scenario_id: "3"},
  {title: "Bit by bit", body: "<div>In the title put:</div><pre>Formatting Ahoy!</pre><div><br>Here we will explore some of these formatting buttons. &nbsp;<br>B is for<strong>&nbsp;bold<br></strong>I is for&nbsp;<em>italic<br></em><del>S</del>&nbsp;is to add a&nbsp;<del>strike through</del><br><br>The chain means that if you select some text and add a hyperlink to them<br>write in the box,</div><pre> ricky ticky tavy </pre><div>Then high light it and click the hyperlink button.<br>What pops up allows you to add your own hyperlink.<br><br>h3 - this sets your text to the styling of Heading 3&nbsp;<br>this is big text and what we most use in EE to maker different sections of a web page<br><br>h4 - this is big text but smaller than h3<br>this text is used for sub sections or sub headings for a web page<br><br>Try out these different formatting in the open area don't be afraid to mess around. &nbsp;when you are finished hit the create entry button at the bottom</div>", information: "", scenario_id: "3"},
  {title: "Wrap around", body: "<div>Make this title:</div><pre>Putting a bow on it</pre><div><br>Sometimes we want to wrap text in a certain format to give us a specific look.<br>In this scenario We've used the &lt;/&gt; button to create pockets of&nbsp;</div><pre>code information!! :D</pre><div><br>We haven't used the quotes button yet.&nbsp; Write some text in the big text area and while at the end of the line of text hit the quotes button<br><br></div><blockquote>Hello i'm dave</blockquote><div><br>You should see it pop towards the middle like the text above.&nbsp; You can escape the quote by hitting the enter button twice.<br><br>Next is the bullets button.&nbsp; We say if you have a list and the order doesn't matter, always use bullets.<br><br>Try adding some bullets to the large text area and make a short list for yourself.</div>", information: "", scenario_id: "3"},
  {title: "The home stretch", body: "<div>Make the title of this entry</div><pre>I can see the light!</pre><div><br>We are nearly at the end of our train ride through navigating this editor.&nbsp; after the bullets is the ordered list button.&nbsp; Ordered lists are numbered and if something has a specific order then and only then should you use one of these.&nbsp;<br><br>With both types of lists you get a piece of indented text. &nbsp;<br><br>create a list of your favorite foods using the bullets.<br><br>when you make the first one you see that a new button lights up and becomes active.</div><ul><li>here</li></ul><div><br>If you click this newly active button it will take away the bullet point.<br><br>While you still have a bullet with text next to it, hit enter.<br><br>Now you have two bullets and another button lit up.&nbsp; If you click this button it will further indent your bullet.</div><ul><li>here<ul><li>there</li></ul></li></ul><div><br>You can keep doing this as much as you want!!! &nbsp;try this with both the ordered and unordered lists and once you feel content click the create entry button at the bottom for your last portion of our introductory scenario!</div>", information: "", scenario_id: "3"},
  {title: "Finally... images?", body: "<div>So our last buttons are pretty straight forward.&nbsp; If you want to add a picture just click the picture button, put in the URL of that picture and a height and boom! the picture shows up.&nbsp; Just try and find small pictures if you want to put some in... somethings don't scale well.<br><br><br>The last two should be familiar undo and redo buttons, cause hey we all make mistakes... sometimes... rght?</div>", information: "", scenario_id: "3"},
  {title: "Here is where this is", body: "<div>HOw about that yo!<br><br>This part is easy with the right thigns!</div>", information: "", scenario_id: "3"}
])

Scenario.create!([
  {title: "Here is where it is`", description: "Going to bump up jo go"},
  {title: "Welcoming Scenario", description: "Welcome to the EE training application.  Click here to get a quick tour of what kinds of things you'll find in this application."},
  {title: "There is more!", description: "HAHAHAHAHA"},
  {title: "Endo crumpas go", description: "mlksjdlkjsfsdf"}
])
